# FINAL PROJECT - Build DataBase

In [2]:
import kaggle
import pandas as pd
import csv
import os
import json
from lets_plot import *
from lets_plot.mapping import *
LetsPlot.setup_html()
#from plotnine import *
from dotenv import dotenv_values

In [5]:
download_path = r'data_proj'
csv_file = [file for file in os.listdir(download_path) if file.endswith('.csv')][0]
csv_path = os.path.join(download_path, csv_file)
df1 = pd.read_csv(csv_path)
df1.shape

(276529, 15)

In [6]:
df1.head()

,CrimeDate,CrimeTime,CrimeCode,Location,Description,Inside/Outside,Weapon,Post,District,Neighborhood,Longitude,Latitude,Location 1,Premise,Total Incidents
0,09/02/2017,23:30:00,3JK,4200 AUDREY AVE,ROBBERY - RESIDENCE,I,KNIFE,913.0,SOUTHERN,Brooklyn,-76.60541,39.22951,"(39.2295100000, -76.6054100000)",ROW/TOWNHO,1
1,09/02/2017,23:00:00,7A,800 NEWINGTON AVE,AUTO THEFT,O,NaN,133.0,CENTRAL,Reservoir Hill,-76.63217,39.31360,"(39.3136000000, -76.6321700000)",STREET,1
2,09/02/2017,22:53:00,9S,600 RADNOR AV,SHOOTING,Outside,FIREARM,524.0,NORTHERN,Winston-Govans,-76.60697,39.34768,"(39.3476800000, -76.6069700000)",Street,1
3,09/02/2017,22:50:00,4C,1800 RAMSAY ST,AGG. ASSAULT,I,OTHER,934.0,SOUTHERN,Carrollton Ridge,-76.64526,39.28315,"(39.2831500000, -76.6452600000)",ROW/TOWNHO,1
4,09/02/2017,22:31:00,4E,100 LIGHT ST,COMMON ASSAULT,O,HANDS,113.0,CENTRAL,Downtown West,-76.61365,39.28756,"(39.2875600000, -76.6136500000)",STREET,1

In [7]:
df1=df1.drop(columns=['CrimeCode','Inside/Outside','Weapon','Post','District','Location 1','Premise'])
df1['City'] = 'Blatimore'
df1

,CrimeDate,CrimeTime,Location,Description,Neighborhood,Longitude,Latitude,Total Incidents,City
0,09/02/2017,23:30:00,4200 AUDREY AVE,ROBBERY - RESIDENCE,Brooklyn,-76.60541,39.22951,1,Blatimore
1,09/02/2017,23:00:00,800 NEWINGTON AVE,AUTO THEFT,Reservoir Hill,-76.63217,39.31360,1,Blatimore
2,09/02/2017,22:53:00,600 RADNOR AV,SHOOTING,Winston-Govans,-76.60697,39.34768,1,Blatimore
3,09/02/2017,22:50:00,1800 RAMSAY ST,AGG. ASSAULT,Carrollton Ridge,-76.64526,39.28315,1,Blatimore
4,09/02/2017,22:31:00,100 LIGHT ST,COMMON ASSAULT,Downtown West,-76.61365,39.28756,1,Blatimore
...,...,...,...,...,...,...,...,...,...
276524,01/01/2012,00:00:00,1400 JOH AVE,LARCENY,Violetville,-76.67195,39.26132,1,Blatimore
276525,01/01/2012,00:00:00,5500 SINCLAIR LN,LARCENY,Frankford,-76.53829,39.32493,1,Blatimore
276526,01/01/2012,00:00:00,400 N PATTERSON PK AV,LARCENY,CARE,-76.58497,39.29573,1,Blatimore
276527,01/01/2012,00:00:00,5800 LILLYAN AV,BURGLARY,Glenham-Belhar,-76.54578,39.34701,1,Blatimore
276528,01/01/2012,00:00:00,1900 GRINNALDS AV,BURGLARY,Morrell Park,-76.65094,39.26698,1,Blatimore

In [8]:
df2 = pd.read_csv('data_proj/crime.csv')
df2.head()

,TYPE,YEAR,MONTH,DAY,HOUR,MINUTE,HUNDRED_BLOCK,NEIGHBOURHOOD,X,Y,Latitude,Longitude
0,Other Theft,2003,5,12,16.0,15.0,9XX TERMINAL AVE,Strathcona,493906.5,5457452.47,49.269802,-123.083763
1,Other Theft,2003,5,7,15.0,20.0,9XX TERMINAL AVE,Strathcona,493906.5,5457452.47,49.269802,-123.083763
2,Other Theft,2003,4,23,16.0,40.0,9XX TERMINAL AVE,Strathcona,493906.5,5457452.47,49.269802,-123.083763
3,Other Theft,2003,4,20,11.0,15.0,9XX TERMINAL AVE,Strathcona,493906.5,5457452.47,49.269802,-123.083763
4,Other Theft,2003,4,12,17.0,45.0,9XX TERMINAL AVE,Strathcona,493906.5,5457452.47,49.269802,-123.083763

In [9]:
df2['CrimeDate'] = pd.to_datetime(df2['DAY'].astype(str) + '/' + df2['MONTH'].astype(str) + '/' + df2['YEAR'].astype(str), format='%d/%m/%Y')
df2['CrimeDate'] = df2['CrimeDate'].dt.strftime('%d/%m/%Y')
df2 = df2.dropna(subset=['HOUR', 'MINUTE'])
df2['HOUR'] = df2['HOUR'].astype(int).astype(str).str.zfill(2)
df2['MINUTE'] = df2['MINUTE'].astype(int).astype(str).str.zfill(2)
df2['CrimeTime'] = pd.to_datetime(df2['HOUR'] + ':' + df2['MINUTE'], format='%H:%M').dt.time
df2=df2.drop(columns=['YEAR','MONTH','DAY','HOUR','MINUTE','X','Y'])
df2['Total Incidents'] = 1
df2['City'] = 'Vancouver'

df2

,TYPE,HUNDRED_BLOCK,NEIGHBOURHOOD,Latitude,Longitude,CrimeDate,CrimeTime,Total Incidents,City
0,Other Theft,9XX TERMINAL AVE,Strathcona,49.269802,-123.083763,12/05/2003,16:15:00,1,Vancouver
1,Other Theft,9XX TERMINAL AVE,Strathcona,49.269802,-123.083763,07/05/2003,15:20:00,1,Vancouver
2,Other Theft,9XX TERMINAL AVE,Strathcona,49.269802,-123.083763,23/04/2003,16:40:00,1,Vancouver
3,Other Theft,9XX TERMINAL AVE,Strathcona,49.269802,-123.083763,20/04/2003,11:15:00,1,Vancouver
4,Other Theft,9XX TERMINAL AVE,Strathcona,49.269802,-123.083763,12/04/2003,17:45:00,1,Vancouver
...,...,...,...,...,...,...,...,...,...
530646,Mischief,14XX E HASTINGS ST,Grandview-Woodland,49.281276,-123.074746,18/01/2017,14:44:00,1,Vancouver
530647,Break and Enter Residential/Other,31XX ADANAC ST,Hastings-Sunrise,49.277420,-123.037595,03/03/2017,09:16:00,1,Vancouver
530648,Mischief,14XX E 7TH AVE,Grandview-Woodland,49.264163,-123.075129,29/05/2017,22:30:00,1,Vancouver
530650,Theft from Vehicle,8XX HAMILTON ST,Central Business District,49.278168,-123.117031,05/06/2017,17:00:00,1,Vancouver
530651,Vehicle Collision or Pedestrian Struck (with I...,13XX BLOCK PARK DR,Marpole,49.215706,-123.134512,06/06/2017,17:38:00,1,Vancouver

In [10]:
print(df1.columns.tolist()) 
print(df2.columns.tolist())

['CrimeDate', 'CrimeTime', 'Location', 'Description', 'Neighborhood', 'Longitude', 'Latitude', 'Total Incidents', 'City']
['TYPE', 'HUNDRED_BLOCK', 'NEIGHBOURHOOD', 'Latitude', 'Longitude', 'CrimeDate', 'CrimeTime', 'Total Incidents', 'City']

In [11]:
df2=df2.rename(columns={'TYPE':'Description','HUNDRED_BLOCK':'Location','NEIGHBOURHOOD':'Neighborhood'})

In [12]:
print(df1.columns.tolist()) 
print(df2.columns.tolist())

['CrimeDate', 'CrimeTime', 'Location', 'Description', 'Neighborhood', 'Longitude', 'Latitude', 'Total Incidents', 'City']
['Description', 'Location', 'Neighborhood', 'Latitude', 'Longitude', 'CrimeDate', 'CrimeTime', 'Total Incidents', 'City']

In [13]:
df_merged = pd.concat([df1, df2], ignore_index=True)

In [14]:
df_merged

,CrimeDate,CrimeTime,Location,Description,Neighborhood,Longitude,Latitude,Total Incidents,City
0,09/02/2017,23:30:00,4200 AUDREY AVE,ROBBERY - RESIDENCE,Brooklyn,-76.605410,39.229510,1,Blatimore
1,09/02/2017,23:00:00,800 NEWINGTON AVE,AUTO THEFT,Reservoir Hill,-76.632170,39.313600,1,Blatimore
2,09/02/2017,22:53:00,600 RADNOR AV,SHOOTING,Winston-Govans,-76.606970,39.347680,1,Blatimore
3,09/02/2017,22:50:00,1800 RAMSAY ST,AGG. ASSAULT,Carrollton Ridge,-76.645260,39.283150,1,Blatimore
4,09/02/2017,22:31:00,100 LIGHT ST,COMMON ASSAULT,Downtown West,-76.613650,39.287560,1,Blatimore
...,...,...,...,...,...,...,...,...,...
752814,18/01/2017,14:44:00,14XX E HASTINGS ST,Mischief,Grandview-Woodland,-123.074746,49.281276,1,Vancouver
752815,03/03/2017,09:16:00,31XX ADANAC ST,Break and Enter Residential/Other,Hastings-Sunrise,-123.037595,49.277420,1,Vancouver
752816,29/05/2017,22:30:00,14XX E 7TH AVE,Mischief,Grandview-Woodland,-123.075129,49.264163,1,Vancouver
752817,05/06/2017,17:00:00,8XX HAMILTON ST,Theft from Vehicle,Central Business District,-123.117031,49.278168,1,Vancouver
752818,06/06/2017,17:38:00,13XX BLOCK PARK DR,Vehicle Collision or Pedestrian Struck (with I...,Marpole,-123.134512,49.215706,1,Vancouver

In [15]:
value_counts = df_merged['Description'].value_counts()

print(value_counts)

Description
Theft from Vehicle                                        172700
Mischief                                                   70413
Break and Enter Residential/Other                          60862
LARCENY                                                    60528
Other Theft                                                52167
COMMON ASSAULT                                             45518
BURGLARY                                                   42538
Theft of Vehicle                                           38418
LARCENY FROM AUTO                                          36295
Break and Enter Commercial                                 33845
AGG. ASSAULT                                               27513
AUTO THEFT                                                 26838
Theft of Bicycle                                           25730
Vehicle Collision or Pedestrian Struck (with Injury)       21901
ROBBERY - STREET                                           17691
ROBBERY - COMMERCIAL                                        4141
ASSAULT BY THREAT                                           3503
SHOOTING                                                    2910
ROBBERY - RESIDENCE                                         2866
RAPE                                                        1637
HOMICIDE                                                    1559
ROBBERY - CARJACKING                                        1528
ARSON                                                       1464
Vehicle Collision or Pedestrian Struck (with Fatality)       254
Name: count, dtype: int64

In [16]:
replace_dict = {
    'Theft from Vehicle': 'Theft',
    'Mischief': 'Mischief',
    'Break and Enter Residential/Other': 'Burglary',
    'LARCENY': 'Larency',
    'Other Theft': 'Theft',
    'COMMON ASSAULT': 'Assault',
    'BURGLARY': 'Burglary',
    'Theft of Vehicle': 'Theft',
    'LARCENY FROM AUTO': 'Larency',
    'Break and Enter Commercial': 'Burglary',
    'AGG. ASSAULT': 'Assault',
    'AUTO THEFT': 'Theft',
    'Theft of Bicycle': 'Theft',
    'Vehicle Collision or Pedestrian Struck (with Injury)': 'Accident',
    'ROBBERY - STREET': 'Robbery',
    'ROBBERY - COMMERCIAL': 'Robbery',
    'ASSAULT BY THREAT': 'Assault',
    'SHOOTING': 'Homicide',
    'ROBBERY - RESIDENCE': 'Robbery',
    'RAPE': 'Rape',
    'HOMICIDE': 'Homicide',
    'ROBBERY - CARJACKING': 'Robbery',
    'ARSON': 'Arson',
    'Vehicle Collision or Pedestrian Struck (with Fatality)': 'Accident'
}

df_merged['Description'] = df_merged['Description'].replace(replace_dict)

In [17]:
df_merged

,CrimeDate,CrimeTime,Location,Description,Neighborhood,Longitude,Latitude,Total Incidents,City
0,09/02/2017,23:30:00,4200 AUDREY AVE,Robbery,Brooklyn,-76.605410,39.229510,1,Blatimore
1,09/02/2017,23:00:00,800 NEWINGTON AVE,Theft,Reservoir Hill,-76.632170,39.313600,1,Blatimore
2,09/02/2017,22:53:00,600 RADNOR AV,Homicide,Winston-Govans,-76.606970,39.347680,1,Blatimore
3,09/02/2017,22:50:00,1800 RAMSAY ST,Assault,Carrollton Ridge,-76.645260,39.283150,1,Blatimore
4,09/02/2017,22:31:00,100 LIGHT ST,Assault,Downtown West,-76.613650,39.287560,1,Blatimore
...,...,...,...,...,...,...,...,...,...
752814,18/01/2017,14:44:00,14XX E HASTINGS ST,Mischief,Grandview-Woodland,-123.074746,49.281276,1,Vancouver
752815,03/03/2017,09:16:00,31XX ADANAC ST,Burglary,Hastings-Sunrise,-123.037595,49.277420,1,Vancouver
752816,29/05/2017,22:30:00,14XX E 7TH AVE,Mischief,Grandview-Woodland,-123.075129,49.264163,1,Vancouver
752817,05/06/2017,17:00:00,8XX HAMILTON ST,Theft,Central Business District,-123.117031,49.278168,1,Vancouver
752818,06/06/2017,17:38:00,13XX BLOCK PARK DR,Accident,Marpole,-123.134512,49.215706,1,Vancouver

In [18]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 752819 entries, 0 to 752818
Data columns (total 9 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   CrimeDate        752819 non-null  object
 1   CrimeTime        752819 non-null  object
 2   Location         750599 non-null  object
 3   Description      752819 non-null  object
 4   Neighborhood     747817 non-null  object
 5   Longitude        750615 non-null  float64
 6   Latitude         750615 non-null  float64
 7   Total Incidents  752819 non-null  int64
 8   City             752819 non-null  object
dtypes: float64(2), int64(1), object(6)
memory usage: 51.7+ MB

In [19]:
df_merged['CrimeDate'] = pd.to_datetime(df_merged['CrimeDate'], infer_datetime_format=True, errors='coerce')

C:\Users\PC\AppData\Local\Temp\ipykernel_2636\4187015635.py:1: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  df_merged['CrimeDate'] = pd.to_datetime(df_merged['CrimeDate'], infer_datetime_format=True, errors='coerce')

In [21]:
df_merged.to_csv('data_proj/final_df.csv', index = False)